first_chromosome = argument[0]
second_chromosome = argument[1]

first_layer_synapses = calculate_expressed_genes_for_layer(first_chromosome.first_layer_synapses,first_chromosome.first_layer_genetic_dominance_array,second_chromosome.first_layer_synapses,second_chromosome.first_layer_genetic_dominance_array)

second_layer_synapses = calculate_expressed_genes_for_layer(first_chromosome.second_layer_synapses,first_chromosome.second_layer_genetic_dominance_array,second_chromosome.second_layer_synapses,second_chromosome.second_layer_genetic_dominance_array)

output_layer_synapses = calculate_expressed_genes_for_layer(first_chromosome.output_layer_synapses,first_chromosome.output_layer_genetic_dominance_array,second_chromosome.output_layer_synapses,second_chromosome.output_layer_genetic_dominance_array)


